name: settheoryapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animated_splash_screen: ^1.3.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  cupertino_icons: ^1.0.6
  audioplayers: ^6.0.0
  flutter_tts: ^3.6.3
  flutter_animate: ^4.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Lottie/set.json
    - assets/audio/background.mp3
    - assets/images/splashscreen.png
    - assets/images/3.png
    - assets/images/2.png
    - assets/images/top.jpg
    - assets/images/settheory.png
    - assets/images/settheory1.png
    - assets/images/settheory2.png
    - assets/images/settheory3.png
    - assets/images/studyicon.png
    - assets/images/quizicon.png
    - assets/images/solveicon.png
    - assets/images/progress.png
    - assets/images/play.png
    - assets/images/teacher.png
    - assets/images/fruits.jpg
    - assets/images/flowers.jpg
    - assets/images/animals.jpg
    - assets/images/apple.png
    - assets/images/orange.png
    - assets/images/strawberry.png
    - assets/images/solution2.png
    - assets/images/solution3.png
    - assets/images/nullset.png
    - assets/images/empty1.png
    - assets/images/empty2.png
    - assets/images/nullset1.png
    - assets/images/unionset.jpg
    - assets/images/set1.jpg
    - assets/images/set2.jpg
    - assets/images/unionlogo.jpg
    - assets/images/B1.png
    - assets/images/disjointset.png
    - assets/images/dset1.png
    - assets/images/dset2.png
    - assets/images/equalset.png
    - assets/images/ds1.png
    - assets/images/ds2.png
    - assets/images/ds3.png
    - assets/images/ds4.png
    - assets/images/ds5.png
    - assets/images/ds6.png
    - assets/images/ds7.png
    - assets/images/ds8.png
    - assets/images/ds9.png
    - assets/images/ds10.png
    - assets/images/ds11.png
    - assets/images/ds12.png
    - assets/images/ds13.png
    - assets/images/ds14.png
    - assets/images/ds15.png
    - assets/images/ds16.png
    - assets/images/ds17.png
    - assets/images/ds18.png
    - assets/images/

    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
